### ISSUE TITLE
jQuery alternatives

### ISSUE THREAD

**Issue by StreetStrider** [petk/awesome-jquery#25]
I propose a section related to jQuery-compatible *alternatives*. Found in list only slight reference to Zepto and Cheerio.
There must be a bold section with at least cash, zepto, cheerio (and possible more to find).

**Comment by petk** [comment]
@StreetStrider sorry I've missed this one... Yes, the alternatives sounds good. Might even sense to create awesome-zepto or awesome-cheerio if such need comes but I can add such section if needed... Pull request is welcome. Thanks.

**Comment by StreetStrider** [comment]
@petk what do you think on duplicating cheerio both in Alternatives and Server-Side sections?
I saw that's against current linting rules, but it makes sence. People can possibly look for it in both categories. Besides, cheerio is a bold jQuery flavor (alternative), just server-side one.
